name: Check And Sync README

on:
  push:
    branches: [ "default" ]

jobs:
  - name: Check For Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v1
        branch: default
      - name: Check if README has changed
        shell: bash
        run: |
          git fetch origin default:main -c rename-sourceref=origin/main
          files_modified=(git ls-files --diff --cached "files/README.md")
          if [ "$files_modified" ]; then
            echo "Changes detected in README.md"
            exit 0
          else
            echo "No changes in README.md"
            exit 1
          fi
      - name: Sync README to main branch
        shell: bash
        run: |
          git checkout main
          rm -r files/README.md
          git checkout main -- files/README.md
