name: Check And Sync README

on:
  push:
    branches: [ "default" ]

jobs:
  - name: Check For Updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout default branch
        branch: default
      - name: Check if README has changed
        shell: bash
        run: |
          git fetch origin default:main -c rename-sourceref=origin/main
          if [ -z "$(git diff -- files/README.md)" ]; then
            echo "No changes in README.md"
            exit 0
          else
            echo "Changes detected, proceeding to sync..."
          fi
      - name: Sync README to main branch
        shell: bash
        run: |
          git checkout main -b temp-feature
          git merge --no-ff origin/main:default/README.md
          git checkout main
          rm -rf temp-feature .git_cache
