name: 定时同步 README

on:
  # 定时任务，每天北京时间0点运行（UTC时间为前一天16:00）
  schedule:
    - cron: '40 10 * * *'
  
  # 手动触发选项
  workflow_dispatch:
  
  # 添加 push 事件，使工作流在推送到任何分支时显示
  push:
    paths:
      - '.github/workflows/copy-readme.yml'

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    
    steps:
      # 检出仓库代码，直接检出 main 分支
      - name: 检出 main 分支
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      
      # 配置 Git 用户信息
      - name: 配置 Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      # 从 README 分支获取 README.md 并覆盖 main 分支中的文件
      - name: 从 README 分支获取 README.md
        run: |
          # 获取 README 分支最新内容
          git fetch origin README
          
          # 从 README 分支复制 README.md 文件到当前工作目录
          git checkout origin/README -- README.md
          
          # 检查是否有更改
          if git diff --staged --quiet; then
            echo "README.md 没有变化，无需更新"
            exit 0
          fi
          
          # 提交更改
          git commit -m "从默认分支更新文档"
          
      # 延迟推送，确保 Pages 任务执行完毕
      - name: 延迟推送避免影响 Pages
        run: |
          echo "等待 60 秒，确保 Pages 任务完成..."
          sleep 60
          git push origin main
