name: 自动复制 README.md

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "要运行的分支"
        required: true
        default: "main"
  
  # 定时任务，每天北京时间0点运行（UTC时间为前一天16:00）
  schedule:
    - cron: '0 16 * * *'
  
  # 添加 push 事件，使工作流在推送到任何分支时显示
  push:
    paths:
      - '.github/workflows/copy-readme.yml'

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    
    steps:
      # 检出仓库代码，直接检出 main 分支
      - name: 检出 main 分支
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      
      # 配置 Git 用户信息
      - name: 配置 Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      # 从 README 分支获取 README.md 并覆盖 main 分支中的文件
      - name: 从 README 分支获取 README.md
        run: |
          git fetch origin README
          git checkout origin/README -- README.md
          
          # 检查是否有更改
          if git diff --quiet README.md; then
            echo "README.md 没有变化，无需更新"
            exit 0
          fi
          
          # 添加更改并提交
          git add README.md
          git commit -m "更新 README 文档"
      
      # 延迟推送，确保 Pages 任务执行完毕
      - name: 延迟推送避免影响 Pages
        run: |
          echo "等待 60 秒，确保 Pages 任务完成..."
          sleep 60
          git push origin main
