name: Sync Shadowrocket Files

on:
  schedule:
    # 每日6点（UTC时间）
    - cron: '0 6 * * *'
  
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出 Shadowrocket 仓库
      - name: Checkout Shadowrocket Repo
        uses: actions/checkout@v4
        with:
          repository: LOWERTOP/Shadowrocket
          ref: main
          path: shadowrocket_repo

      # 检出当前仓库
      - name: Checkout Current Repo
        uses: actions/checkout@v4
        with:
          ref: main
          path: current_repo

      # 删除 OfficialFiles 目录中的旧文件
      - name: Delete Old Files in OfficialFiles
        run: |
          rm -rf current_repo/OfficialFiles/*

      # 同步 lazy.conf 和 lazy_group.conf
      - name: Sync lazy.conf and lazy_group.conf
        run: |
          cp shadowrocket_repo/lazy.conf current_repo/OfficialFiles/
          cp shadowrocket_repo/lazy_group.conf current_repo/OfficialFiles/

      # 重命名 README.md 为 Manual.md 并同步
      - name: Rename README.md to Manual.md and Sync
        run: |
          mv shadowrocket_repo/README.md current_repo/OfficialFiles/Manual.md

      # 提交并推送更新到当前仓库
      - name: Commit and Push Changes
        run: |
          cd current_repo
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Sync files from Shadowrocket repo"
          git push
