name: Release Shadowrocket Rules

on:
  schedule:
    # 每日8时开始
    - cron:  '0 23 * * *'
  
  push:
    branches:
      - build
    paths-ignore: 
      - '**.md'
      - 'LICENSE'
      
  pull_request_target:
    branches:
      - build
    paths-ignore: 
      - '**.md'
      - 'LICENSE'

  workflow_dispatch:  # 允许手动运行工作流
  
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: build
          path: build

      - uses: actions/checkout@v4
        with:
          ref: release
          path: release

      - name: Update lazy rules
        run: |
          cd release || exit 1
          rm lazy.conf lazy_group.conf
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy.conf
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy_group.conf

      - name: Download and rename README
        run: |
          cd release || exit 1
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/README.md
          mv README.md Manual.md

      - name: Move files to OfficialFiles directory
        run: |
          cd release || exit 1
          mkdir -p OfficialFiles
          cp lazy.conf lazy_group.conf Manual.md ../release/OfficialFiles/

      - name: Remove commits
        run: |
          cd release || exit 1
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan latest_branch
          git add -A
          git commit -am "Nightly build"
          git branch -D release
          git branch -m release
          git push -f origin release
