name: Official Files Update

on:
  schedule:
    # 每日北京时间6时（即UTC 10时）开始
    - cron:  '0 10 * * *'
  
  workflow_dispatch:  # 允许手动运行工作流
  
jobs:
  UpdateFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # 检出 main 分支

      - name: Update lazy rules
        run: |
          # 在当前目录中下载 lazy.conf 和 lazy_group.conf 文件
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy.conf
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy_group.conf

      - name: Download and rename README
        run: |
          # 下载 README.md 文件并重命名为 Manual.md
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/README.md
          mv README.md Manual.md

      - name: Move files to OfficialFiles directory
        run: |
          # 创建 OfficialFiles 目录（如果不存在的话）
          mkdir -p OfficialFiles
          
          # 将文件移动到 OfficialFiles 目录
          mv lazy.conf lazy_group.conf Manual.md OfficialFiles/
