name: Force Sync Files from Shadowrocket

on:
  schedule:
    - cron: '0 22 * * *'  # UTC时间22点（北京时间6点）
  workflow_dispatch:  # 可选：允许手动触发

jobs:
  force-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Shadowrocket-First
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target

      - name: Download 和 Overwrite Files
        run: |
          # 强制创建/覆盖目标目录
          mkdir -p target/OfficialFiles
          # 删除旧版官方文件
          rm target/OfficialFiles/lazy.conf target/OfficialFiles/lazy_group.conf target/OfficialFiles/Manual.md

          # 使用原始链接下载文件（强制覆盖）
          curl -o target/OfficialFiles/lazy.conf "https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy.conf?$(date +%s)"
          curl -o target/OfficialFiles/lazy_group.conf "https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy_group.conf?$(date +%s)"
          curl -o target/OfficialFiles/Manual.md "https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/README.md?$(date +%s)"

      - name: Force Commit 和 Push
        run: |
          cd target
          # 配置为 github-actions[bot] 身份
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 强制添加所有更改（包括未修改的文件）
          git add --force OfficialFiles/
          
          # 生成时间戳确保每次提交不同
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # 强制提交（无论文件是否变化）
          git commit --allow-empty -m "Force Sync at ${TIMESTAMP}"
          
          # 强制推送覆盖远程
          git push --force origin HEAD
