name: Translate README

on:
  workflow_dispatch:   # 手动触发工作流
  push:
    paths:
      - README.md

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run translation script
        env:
          DEEPOSEEK_API_KEY: ${{ secrets.DEEPOSEEK_API_KEY }}
        run: python translate.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.EN.MD
          git commit -m "Update English translation of README" || echo "No changes to commit"
          git push
